"""Chess piece classes and pseudo-legal move generation."""

class Piece:
    """Base class for chess pieces.

    Attributes:
        color (str): Piece color, either "w" or "b".
        symbol (str): Single-letter symbol used in notation and UI output.
    """

    def __init__(self, color):
        """Create a piece with the given color.

        Args:
            color (str): Piece color, either "w" or "b".
        """
        self.color = color

    def get_moves(self, pos, board):
        """Return pseudo-legal moves for the piece from a position.

        Args:
            pos (tuple[int, int]): Current (row, col) coordinates.
            board: Board-like object providing piece lookup via grid.

        Returns:
            list[tuple[int, int]]: Candidate destination squares.
        """

    def _sliding_moves(self, pos, board, directions):
        """Return moves generated by sliding along the given directions."""
        moves = []
        row, col = pos
        grid = board.grid

        for dr, dc in directions:
            new_row = row + dr
            new_col = col + dc

            while 0 <= new_row < 8 and 0 <= new_col < 8:
                target = grid[new_row][new_col]
                if target is None:
                    moves.append((new_row, new_col))
                    new_row += dr
                    new_col += dc
                    continue

                if target.color != self.color:
                    moves.append((new_row, new_col))
                break

        return moves

    symbol = "?"
    def __str__(self):
        """Return the compact color-and-symbol representation."""
        return f"{self.color}{self.symbol}"


class Pawn(Piece):
    """Pawn move generation including captures and en passant."""

    symbol = "P"
    def get_moves(self, pos, board):
        """Return pseudo-legal pawn moves from (pos).

        Args:
            pos (tuple[int, int]): Pawn position as (row, col).
            board: Board containing the pawn and target squares.

        Returns:
            list[tuple[int, int]]: Forward moves and capture squares,
                including en passant targets when available.
        """
        moves = []
        row, col = pos

        grid = board.grid
        en_passant_target = getattr(board, "en_passant_target", None)

        direction = -1 if self.color == "w" else 1
        start_row = 6 if self.color == "w" else 1

        new_row = row + direction
        if 0 <= new_row < 8 and grid[new_row][col] is None:
            moves.append((new_row, col))
            new_row2 = row + 2 * direction
            if row == start_row and 0 <= new_row2 < 8 and grid[new_row2][col] is None:
                moves.append((new_row2, col))

        for diag in [-1, 1]:
            new_col = col + diag
            if 0 <= new_col < 8 and 0 <= new_row < 8:
                target = grid[new_row][new_col]
                if target is not None and target.color != self.color:
                    moves.append((new_row, new_col))
                if en_passant_target is not None and (new_row, new_col) == en_passant_target:
                    moves.append((new_row, new_col))

        return moves



class Knight(Piece):
    """Knight move generation."""

    symbol = "N"
    def get_moves(self, pos, board):
        """Return pseudo-legal knight moves from (pos)."""
        moves = []
        row, col = pos

        grid = board.grid

        directions = [(1, 2), (1, -2), (-1, 2), (-1, -2), (2, 1), (2, -1), (-2, 1), (-2, -1)]
        for d in directions:
            new_row = row + d[0]
            new_col = col + d[1]
            if 0 <= new_col < 8 and 0 <= new_row < 8:
                target = grid[new_row][new_col]
                if target is None or (target and target.color != self.color):
                    moves.append((new_row, new_col))

        return moves

class Bishop(Piece):
    """Bishop move generation along diagonals."""

    symbol = "B"
    def get_moves(self, pos, board):
        """Return pseudo-legal bishop moves from (pos)."""
        directions = [(1, 1), (-1, 1), (-1, -1), (1, -1)]
        return self._sliding_moves(pos, board, directions)

class Rook(Piece):
    """Rook move generation along ranks and files.

    Attributes:
        has_moved (bool): Tracks castling eligibility.
    """

    symbol = "R"
    has_moved = False

    def get_moves(self, pos, board):
        """Return pseudo-legal rook moves from (pos)."""
        directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
        return self._sliding_moves(pos, board, directions)

class Queen(Piece):
    """Queen move generation along ranks, files and diagonals."""

    symbol = "Q"
    def get_moves(self, pos, board):
        """Return pseudo-legal queen moves from (pos)."""
        directions = [(0, 1), (1, 0), (0, -1), (-1, 0), (1, 1), (-1, 1), (-1, -1), (1, -1)]
        return self._sliding_moves(pos, board, directions)

class King(Piece):
    """King move generation including castling candidates.

    Attributes:
        has_moved (bool): Tracks castling eligibility.
    """

    symbol = "K"
    has_moved = False
    def get_moves(self, pos, board):
        """Return pseudo-legal king moves from (pos).

        The returned moves may include castling destinations when the king and
        rook have not moved and the path squares are empty. Check-related
        validation is handled elsewhere.
        """
        moves = []
        row, col = pos

        grid = board.grid

        directions = [(0, 1), (1, 0), (0, -1), (-1, 0), (1, 1), (-1, 1), (-1, -1), (1, -1)]
        for d in directions:
            new_row = row + d[0]
            new_col = col + d[1]
            if 0 <= new_row < 8 and 0 <= new_col < 8:
                target = grid[new_row][new_col]
                if target is None or target.color != self.color:
                    moves.append((new_row, new_col))

        if not self.has_moved:
            rook = grid[row][7]
            if (rook is not None and rook.color == self.color and isinstance(rook, Rook)
                    and not getattr(rook, "has_moved")):
                if grid[row][5] is None and grid[row][6] is None:
                    moves.append((row, 6))

            rook_q = grid[row][0]
            if (rook_q is not None and rook_q.color == self.color and isinstance(rook_q, Rook)
                    and not getattr(rook_q, "has_moved")):
                if grid[row][1] is None and grid[row][2] is None and grid[row][3] is None:
                    moves.append((row, 2))

        return moves
